application: gaehacking
version: 1
runtime: python
api_version: 1

builtins:

- appstats: on

handlers:

- url: /(.*)/static/(.*)
  static_files: \1/static/\2
  upload: (.*)/static/(.*)

- url: /admin/gettweets
  script: addons/gettweets.py
  login: admin

- url: /admin/getphotos
  script: addons/getphotos.py
  login: admin

- url: /admin.*
  script: admin/admin.py
  login: admin

- url: /images.*
  script: images.py

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /.*
  script: main.py
